/* Generated By:JavaCC: Do not edit this line. Analizador_BDTreeConstants.java Version 5.0 */
package XML.BD;

public interface Analizador_BDTreeConstants
{
  public int JJTSTART = 0;
  public int JJTINICIO = 1;
  public int JJTSENTENCIAS = 2;
  public int JJTTABLAS = 3;
  public int JJTRUTA = 4;
  public int JJTPROCEDURE = 5;
  public int JJTOBJETOS = 6;
  public int JJTCOMPE_U = 7;
  public int JJTTIPO = 8;
  public int JJTTIPO_CAMPO = 9;
  public int JJTNOMBRE = 10;
  public int JJTROW = 11;
  public int JJTTABLA = 12;
  public int JJTCOLUMNAS = 13;
  public int JJTCOMPLEMENTO = 14;
  public int JJTTERM_ID = 15;
  public int JJTCADENA = 16;


  public String[] jjtNodeName = {
    "Start",
    "Inicio",
    "sentencias",
    "tablas",
    "ruta",
    "Procedure",
    "Objetos",
    "COMPE_U",
    "Tipo",
    "tipo_campo",
    "nombre",
    "row",
    "tabla",
    "columnas",
    "complemento",
    "term_id",
    "Cadena",
  };
}
/* JavaCC - OriginalChecksum=01501e9faf1eeb528492141d7f74f83e (do not edit this line) */
