/* Generated By:JavaCC: Do not edit this line. Analizador_ProcedureTreeConstants.java Version 5.0 */
package XML.Procedure;

public interface Analizador_ProcedureTreeConstants
{
  public int JJTSTART = 0;
  public int JJTINICIO = 1;
  public int JJTSENTENCIAS = 2;
  public int JJTVOID = 3;
  public int JJTTIPO = 4;
  public int JJTNOMBREV = 5;
  public int JJTATRIBUTO = 6;
  public int JJTPARAMETROS = 7;
  public int JJTCODIGO = 8;
  public int JJTPROCEDIMIENTO = 9;
  public int JJTFUNCION = 10;
  public int JJTTERM_ID = 11;
  public int JJTCADENA = 12;


  public String[] jjtNodeName = {
    "Start",
    "Inicio",
    "sentencias",
    "void",
    "Tipo",
    "NombreV",
    "Atributo",
    "parametros",
    "codigo",
    "Procedimiento",
    "funcion",
    "term_id",
    "Cadena",
  };
}
/* JavaCC - OriginalChecksum=3ae5b47046c97ab3de6f8f0714028bc4 (do not edit this line) */
