/* Generated By:JJTree&JavaCC: Do not edit this line. Analizador_TuplasConstants.java */
package XML.Tuplas_Tabla;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Analizador_TuplasConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int proc = 6;
  /** RegularExpression Id. */
  int abre_etiqueta = 7;
  /** RegularExpression Id. */
  int cierra_etiqueta = 8;
  /** RegularExpression Id. */
  int nombre = 9;
  /** RegularExpression Id. */
  int func = 10;
  /** RegularExpression Id. */
  int diagonal = 11;
  /** RegularExpression Id. */
  int params = 12;
  /** RegularExpression Id. */
  int tip = 13;
  /** RegularExpression Id. */
  int row = 14;
  /** RegularExpression Id. */
  int TEXT = 15;
  /** RegularExpression Id. */
  int INTEGER = 16;
  /** RegularExpression Id. */
  int DOUBLE = 17;
  /** RegularExpression Id. */
  int BOOL = 18;
  /** RegularExpression Id. */
  int DATE = 19;
  /** RegularExpression Id. */
  int DATETIME = 20;
  /** RegularExpression Id. */
  int S_MENOS = 21;
  /** RegularExpression Id. */
  int dos_puntos = 22;
  /** RegularExpression Id. */
  int DECIMAL = 23;
  /** RegularExpression Id. */
  int NUM = 24;
  /** RegularExpression Id. */
  int CADENA = 25;
  /** RegularExpression Id. */
  int CARACTER = 26;
  /** RegularExpression Id. */
  int id = 27;
  /** RegularExpression Id. */
  int LETRA = 28;
  /** RegularExpression Id. */
  int DIGITO = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"proc\"",
    "\"<\"",
    "\">\"",
    "\"nombre\"",
    "\"func\"",
    "\"/\"",
    "\"params\"",
    "\"tipo\"",
    "\"row\"",
    "\"TEXT\"",
    "\"INTEGER\"",
    "\"DOUBLE\"",
    "\"BOOL\"",
    "\"DATE\"",
    "\"DATETIME\"",
    "\"-\"",
    "\":\"",
    "<DECIMAL>",
    "<NUM>",
    "<CADENA>",
    "<CARACTER>",
    "<id>",
    "<LETRA>",
    "<DIGITO>",
  };

}
