/* Generated By:JavaCC: Do not edit this line. Analizador_TuplasTreeConstants.java Version 5.0 */
package XML.Tuplas_Tabla;

public interface Analizador_TuplasTreeConstants
{
  public int JJTSTART = 0;
  public int JJTINICIO = 1;
  public int JJTSENTENCIAS = 2;
  public int JJTCAMPO = 3;
  public int JJTFILA = 4;
  public int JJTVOID = 5;
  public int JJTNEGATIVO = 6;
  public int JJTDECIMAL = 7;
  public int JJTNUMERO = 8;
  public int JJTCADENA = 9;
  public int JJTFECHA = 10;
  public int JJTTERM_ID = 11;


  public String[] jjtNodeName = {
    "Start",
    "Inicio",
    "sentencias",
    "Campo",
    "fila",
    "void",
    "Negativo",
    "Decimal",
    "Numero",
    "Cadena",
    "Fecha",
    "term_id",
  };
}
/* JavaCC - OriginalChecksum=19aa9ffbacd6df8724729e0309f79f4f (do not edit this line) */
