/* Generated By:JavaCC: Do not edit this line. analizadorTreeConstants.java Version 5.0 */
package Analizador;

public interface analizadorTreeConstants
{
  public int JJTSTART = 0;
  public int JJTINICIO = 1;
  public int JJTVOID = 2;
  public int JJTARCHIVO = 3;
  public int JJTTIPO = 4;
  public int JJTL_ATRIBUTOS = 5;
  public int JJTATRIBUTO = 6;
  public int JJTVAR_PARAMETRO = 7;
  public int JJTL_VAR_PARAMETRO = 8;
  public int JJTL_ELEMENTOS = 9;
  public int JJTELEMENTO = 10;
  public int JJTCOMPLEMENTO = 11;
  public int JJTCOMPE_U = 12;
  public int JJTLLAVE_FOR = 13;
  public int JJTL_CREAR = 14;
  public int JJTCREAR = 15;
  public int JJTBASE = 16;
  public int JJTTABLA = 17;
  public int JJTOBJETO = 18;
  public int JJTPROCEDIMIENTO = 19;
  public int JJTFUNCION = 20;
  public int JJTUSUARIO = 21;
  public int JJTUSAR = 22;
  public int JJTL_ID = 23;
  public int JJTALTERAR_TABLA = 24;
  public int JJTALTERAR_AGREGAR_TABLA = 25;
  public int JJTALTERAR_QUITAR_TABLA = 26;
  public int JJTALTERAR_OBJETO = 27;
  public int JJTALTERAR_AGREGAR_OBJETO = 28;
  public int JJTALTERAR_QUITAR_OBJETO = 29;
  public int JJTALTERAR_USUARIO = 30;
  public int JJTALTERAR = 31;
  public int JJTOPCIONES_ALTERAR = 32;
  public int JJTELIMINAR = 33;
  public int JJTOBJETO_USQL = 34;
  public int JJTINSERTAR = 35;
  public int JJTOPCIONES_INSERTAR = 36;
  public int JJTDONDE = 37;
  public int JJTACTUALIZAR = 38;
  public int JJTBORRAR = 39;
  public int JJTSELECCIONAR = 40;
  public int JJTTIPO_SELECCION = 41;
  public int JJTDONDE_ORDEN = 42;
  public int JJTASTERISCO = 43;
  public int JJTORDEN = 44;
  public int JJTBASE_PERMISOS = 45;
  public int JJTOTORGAR = 46;
  public int JJTDENEGAR = 47;
  public int JJTL_VARIABLES = 48;
  public int JJTINSTANCIA = 49;
  public int JJTVARIABLE = 50;
  public int JJTDECLARAR = 51;
  public int JJTCOMPLEMENTO_ASIGNACION = 52;
  public int JJTASIGNACION = 53;
  public int JJTCUERPO = 54;
  public int JJTSI = 55;
  public int JJTSINO = 56;
  public int JJTIF = 57;
  public int JJTUNARIO = 58;
  public int JJTPARA = 59;
  public int JJTMIENTRAS = 60;
  public int JJTDETENER = 61;
  public int JJTIMPRIMIR = 62;
  public int JJTFECHA = 63;
  public int JJTFECHA_HORA = 64;
  public int JJTCONTAR = 65;
  public int JJTBACK_USQLDUMP = 66;
  public int JJTBACK_COMPLETO = 67;
  public int JJTREST_USQLDUMP = 68;
  public int JJTREST_COMPLETO = 69;
  public int JJTCONDICION = 70;
  public int JJTOR = 71;
  public int JJTAND = 72;
  public int JJTNUVA_CONDICIONNOT = 73;
  public int JJTNUVA_CONDICION = 74;
  public int JJTVALORBOOL = 75;
  public int JJTOPERADOR = 76;
  public int JJTEXPRESION = 77;
  public int JJTSUMA = 78;
  public int JJTRESTA = 79;
  public int JJTMULTIPLICACION = 80;
  public int JJTDIVISION = 81;
  public int JJTPOTENCIA = 82;
  public int JJTNEGATIVO = 83;
  public int JJTDECIMAL = 84;
  public int JJTNUMERO = 85;
  public int JJTCADENA = 86;
  public int JJTID = 87;
  public int JJTLLAMADA_FUNCION = 88;
  public int JJTID_EXTRA = 89;
  public int JJTTERM_ID = 90;
  public int JJTPARAMETRO_EXPRESION = 91;


  public String[] jjtNodeName = {
    "Start",
    "Inicio",
    "void",
    "archivo",
    "Tipo",
    "L_ATRIBUTOS",
    "ATRIBUTO",
    "VAR_PARAMETRO",
    "L_VAR_PARAMETRO",
    "L_ELEMENTOS",
    "ELEMENTO",
    "COMPLEMENTO",
    "COMPE_U",
    "LLAVE_FOR",
    "L_CREAR",
    "CREAR",
    "BASE",
    "TABLA",
    "OBJETO",
    "PROCEDIMIENTO",
    "FUNCION",
    "USUARIO",
    "USAR",
    "L_ID",
    "ALTERAR_TABLA",
    "ALTERAR_AGREGAR_TABLA",
    "ALTERAR_QUITAR_TABLA",
    "ALTERAR_OBJETO",
    "ALTERAR_AGREGAR_OBJETO",
    "ALTERAR_QUITAR_OBJETO",
    "ALTERAR_USUARIO",
    "ALTERAR",
    "OPCIONES_ALTERAR",
    "ELIMINAR",
    "OBJETO_USQL",
    "INSERTAR",
    "OPCIONES_INSERTAR",
    "Donde",
    "ACTUALIZAR",
    "BORRAR",
    "SELECCIONAR",
    "Tipo_Seleccion",
    "Donde_Orden",
    "asterisco",
    "Orden",
    "Base_permisos",
    "OTORGAR",
    "DENEGAR",
    "l_variables",
    "INSTANCIA",
    "VARIABLE",
    "DECLARAR",
    "complemento_asignacion",
    "ASIGNACION",
    "CUERPO",
    "SI",
    "SINO",
    "IF",
    "unario",
    "PARA",
    "MIENTRAS",
    "DETENER",
    "IMPRIMIR",
    "FECHA",
    "FECHA_HORA",
    "CONTAR",
    "BACK_USQLDUMP",
    "BACK_COMPLETO",
    "REST_USQLDUMP",
    "REST_COMPLETO",
    "Condicion",
    "Or",
    "And",
    "Nuva_CondicionNOT",
    "Nuva_Condicion",
    "valorBool",
    "Operador",
    "Expresion",
    "Suma",
    "Resta",
    "Multiplicacion",
    "Division",
    "Potencia",
    "Negativo",
    "Decimal",
    "Numero",
    "Cadena",
    "Id",
    "llamada_funcion",
    "id_extra",
    "term_id",
    "Parametro_Expresion",
  };
}
/* JavaCC - OriginalChecksum=a70f0d864b4f87e0172050d2ac472fc0 (do not edit this line) */
