/* Generated By:JavaCC: Do not edit this line. analizadorTreeConstants.java Version 5.0 */
package Analizador;

public interface analizadorTreeConstants
{
  public int JJTSTART = 0;
  public int JJTINICIO = 1;
  public int JJTINSTRUCCION = 2;
  public int JJTVOID = 3;
  public int JJTARCHIVO = 4;
  public int JJTTIPO = 5;
  public int JJTL_ATRIBUTOS = 6;
  public int JJTATRIBUTO = 7;
  public int JJTVAR_PARAMETRO = 8;
  public int JJTL_VAR_PARAMETRO = 9;
  public int JJTL_ELEMENTOS = 10;
  public int JJTELEMENTO = 11;
  public int JJTCOMPLEMENTO = 12;
  public int JJTCOMPE_U = 13;
  public int JJTLLAVE_FOR = 14;
  public int JJTL_CREAR = 15;
  public int JJTCREAR = 16;
  public int JJTBASE = 17;
  public int JJTTABLA = 18;
  public int JJTOBJETO = 19;
  public int JJTPROCEDIMIENTO = 20;
  public int JJTFUNCION = 21;
  public int JJTUSUARIO = 22;
  public int JJTUSAR = 23;
  public int JJTL_ID = 24;
  public int JJTALTERAR_TABLA = 25;
  public int JJTALTERAR_AGREGAR_TABLA = 26;
  public int JJTALTERAR_QUITAR_TABLA = 27;
  public int JJTALTERAR_OBJETO = 28;
  public int JJTALTERAR_AGREGAR_OBJETO = 29;
  public int JJTALTERAR_QUITAR_OBJETO = 30;
  public int JJTALTERAR_USUARIO = 31;
  public int JJTALTERAR = 32;
  public int JJTOPCIONES_ALTERAR = 33;
  public int JJTELIMINAR = 34;
  public int JJTOBJETO_USQL = 35;
  public int JJTINSERTAR = 36;
  public int JJTL_TERM_ID = 37;
  public int JJTOP_CAMPO = 38;
  public int JJTFORMA1 = 39;
  public int JJTFORMA2 = 40;
  public int JJTTABLA_CAMPO = 41;
  public int JJTDONDE = 42;
  public int JJTACTUALIZAR = 43;
  public int JJTBORRAR = 44;
  public int JJTSELECCIONAR = 45;
  public int JJTTIPO_SELECCION = 46;
  public int JJTDONDE_ORDEN = 47;
  public int JJTASTERISCO = 48;
  public int JJTORDEN = 49;
  public int JJTBASE_PERMISOS = 50;
  public int JJTOTORGAR = 51;
  public int JJTDENEGAR = 52;
  public int JJTL_VARIABLES = 53;
  public int JJTINSTANCIA = 54;
  public int JJTVARIABLE = 55;
  public int JJTDECLARAR = 56;
  public int JJTCOMPLEMENTO_ASIGNACION = 57;
  public int JJTASIGNACION = 58;
  public int JJTCUERPO = 59;
  public int JJTSI = 60;
  public int JJTSINO = 61;
  public int JJTIF = 62;
  public int JJTUNARIO = 63;
  public int JJTPARA = 64;
  public int JJTMIENTRAS = 65;
  public int JJTDETENER = 66;
  public int JJTIMPRIMIR = 67;
  public int JJTFECHA = 68;
  public int JJTFECHA_HORA = 69;
  public int JJTCONTAR = 70;
  public int JJTBACK_USQLDUMP = 71;
  public int JJTBACK_COMPLETO = 72;
  public int JJTREST_USQLDUMP = 73;
  public int JJTREST_COMPLETO = 74;
  public int JJTCONDICION = 75;
  public int JJTOR = 76;
  public int JJTAND = 77;
  public int JJTNUVA_CONDICIONNOT = 78;
  public int JJTNUVA_CONDICION = 79;
  public int JJTVALORBOOL = 80;
  public int JJTOPERADOR = 81;
  public int JJTEXPRESION = 82;
  public int JJTSUMA = 83;
  public int JJTRESTA = 84;
  public int JJTMULTIPLICACION = 85;
  public int JJTDIVISION = 86;
  public int JJTPOTENCIA = 87;
  public int JJTLLAMADA = 88;
  public int JJTATRI_OBJ = 89;
  public int JJTVAR = 90;
  public int JJTNEGATIVO = 91;
  public int JJTDECIMAL = 92;
  public int JJTNUMERO = 93;
  public int JJTCADENA = 94;
  public int JJTID = 95;
  public int JJTLLAMADA_FUNCION = 96;
  public int JJTID_EXTRA = 97;
  public int JJTTERM_ID = 98;
  public int JJTPARAMETRO_EXPRESION = 99;


  public String[] jjtNodeName = {
    "Start",
    "Inicio",
    "INSTRUCCION",
    "void",
    "archivo",
    "Tipo",
    "L_ATRIBUTOS",
    "ATRIBUTO",
    "VAR_PARAMETRO",
    "L_VAR_PARAMETRO",
    "L_ELEMENTOS",
    "ELEMENTO",
    "COMPLEMENTO",
    "COMPE_U",
    "LLAVE_FOR",
    "L_CREAR",
    "CREAR",
    "BASE",
    "TABLA",
    "OBJETO",
    "PROCEDIMIENTO",
    "FUNCION",
    "USUARIO",
    "USAR",
    "L_ID",
    "ALTERAR_TABLA",
    "ALTERAR_AGREGAR_TABLA",
    "ALTERAR_QUITAR_TABLA",
    "ALTERAR_OBJETO",
    "ALTERAR_AGREGAR_OBJETO",
    "ALTERAR_QUITAR_OBJETO",
    "ALTERAR_USUARIO",
    "ALTERAR",
    "OPCIONES_ALTERAR",
    "ELIMINAR",
    "OBJETO_USQL",
    "INSERTAR",
    "l_term_id",
    "op_campo",
    "forma1",
    "forma2",
    "tabla_campo",
    "Donde",
    "ACTUALIZAR",
    "BORRAR",
    "SELECCIONAR",
    "Tipo_Seleccion",
    "Donde_Orden",
    "asterisco",
    "Orden",
    "Base_permisos",
    "OTORGAR",
    "DENEGAR",
    "l_variables",
    "INSTANCIA",
    "VARIABLE",
    "DECLARAR",
    "complemento_asignacion",
    "ASIGNACION",
    "CUERPO",
    "SI",
    "SINO",
    "IF",
    "unario",
    "PARA",
    "MIENTRAS",
    "DETENER",
    "IMPRIMIR",
    "FECHA",
    "FECHA_HORA",
    "CONTAR",
    "BACK_USQLDUMP",
    "BACK_COMPLETO",
    "REST_USQLDUMP",
    "REST_COMPLETO",
    "Condicion",
    "Or",
    "And",
    "Nuva_CondicionNOT",
    "Nuva_Condicion",
    "valorBool",
    "Operador",
    "Expresion",
    "Suma",
    "Resta",
    "Multiplicacion",
    "Division",
    "Potencia",
    "LLAMADA",
    "ATRI_OBJ",
    "VAR",
    "Negativo",
    "Decimal",
    "Numero",
    "Cadena",
    "Id",
    "llamada_funcion",
    "id_extra",
    "term_id",
    "Parametro_Expresion",
  };
}
/* JavaCC - OriginalChecksum=83d0510063a84a89fb4135f2ca6fbc11 (do not edit this line) */
