/* Generated By:JJTree&JavaCC: Do not edit this line. Analizador_MaestroConstants.java */
package XML.Maestro;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Analizador_MaestroConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int db = 6;
  /** RegularExpression Id. */
  int abre_etiqueta = 7;
  /** RegularExpression Id. */
  int cierra_etiqueta = 8;
  /** RegularExpression Id. */
  int nombre = 9;
  /** RegularExpression Id. */
  int path = 10;
  /** RegularExpression Id. */
  int diagonal = 11;
  /** RegularExpression Id. */
  int DECIMAL = 12;
  /** RegularExpression Id. */
  int NUM = 13;
  /** RegularExpression Id. */
  int CADENA = 14;
  /** RegularExpression Id. */
  int CARACTER = 15;
  /** RegularExpression Id. */
  int id = 16;
  /** RegularExpression Id. */
  int LETRA = 17;
  /** RegularExpression Id. */
  int DIGITO = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"DB\"",
    "\"<\"",
    "\">\"",
    "\"nombre\"",
    "\"path\"",
    "\"/\"",
    "<DECIMAL>",
    "<NUM>",
    "<CADENA>",
    "<CARACTER>",
    "<id>",
    "<LETRA>",
    "<DIGITO>",
  };

}
