/* Generated By:JavaCC: Do not edit this line. Analizador_MaestroTreeConstants.java Version 5.0 */
package XML.Maestro;

public interface Analizador_MaestroTreeConstants
{
  public int JJTSTART = 0;
  public int JJTINICIO = 1;
  public int JJTSENTENCIAS = 2;
  public int JJTBASE = 3;
  public int JJTTERM_ID = 4;
  public int JJTRUTA = 5;


  public String[] jjtNodeName = {
    "Start",
    "Inicio",
    "sentencias",
    "base",
    "term_id",
    "ruta",
  };
}
/* JavaCC - OriginalChecksum=27ef8f575db60c4f91ae88ef1831479b (do not edit this line) */
