/* Generated By:JavaCC: Do not edit this line. Analizador_ObjectTreeConstants.java Version 5.0 */
package XML.Object;

public interface Analizador_ObjectTreeConstants
{
  public int JJTSTART = 0;
  public int JJTINICIO = 1;
  public int JJTTIPO = 2;
  public int JJTNOMBREV = 3;
  public int JJTATRIBUTO = 4;
  public int JJTOBJETO = 5;
  public int JJTSENTENCIAS = 6;
  public int JJTTERM_ID = 7;


  public String[] jjtNodeName = {
    "Start",
    "Inicio",
    "Tipo",
    "NombreV",
    "Atributo",
    "Objeto",
    "sentencias",
    "term_id",
  };
}
/* JavaCC - OriginalChecksum=aaa8dad9f3973ca137d8032d58beae5a (do not edit this line) */
