/* Generated By:JJTree&JavaCC: Do not edit this line. Analizador_ObjectConstants.java */
package XML.Object;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Analizador_ObjectConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int obj = 6;
  /** RegularExpression Id. */
  int abre_etiqueta = 7;
  /** RegularExpression Id. */
  int cierra_etiqueta = 8;
  /** RegularExpression Id. */
  int nombre = 9;
  /** RegularExpression Id. */
  int attr = 10;
  /** RegularExpression Id. */
  int diagonal = 11;
  /** RegularExpression Id. */
  int TEXT = 12;
  /** RegularExpression Id. */
  int INTEGER = 13;
  /** RegularExpression Id. */
  int DOUBLE = 14;
  /** RegularExpression Id. */
  int BOOL = 15;
  /** RegularExpression Id. */
  int DATE = 16;
  /** RegularExpression Id. */
  int DATETIME = 17;
  /** RegularExpression Id. */
  int DECIMAL = 18;
  /** RegularExpression Id. */
  int NUM = 19;
  /** RegularExpression Id. */
  int CADENA = 20;
  /** RegularExpression Id. */
  int CARACTER = 21;
  /** RegularExpression Id. */
  int id = 22;
  /** RegularExpression Id. */
  int LETRA = 23;
  /** RegularExpression Id. */
  int DIGITO = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"obj\"",
    "\"<\"",
    "\">\"",
    "\"nombre\"",
    "\"attr\"",
    "\"/\"",
    "\"TEXT\"",
    "\"INTEGER\"",
    "\"DOUBLE\"",
    "\"BOOL\"",
    "\"DATE\"",
    "\"DATETIME\"",
    "<DECIMAL>",
    "<NUM>",
    "<CADENA>",
    "<CARACTER>",
    "<id>",
    "<LETRA>",
    "<DIGITO>",
  };

}
